### ISSUE TITLE
Add a magical one day coding party!

### ISSUE THREAD

**Issue by abbyfischler** [hackclub/horizon#3]
Under Hack Club + Girl Scouts present...
create a new line to say

"a magical one day coding party!"

**Comment by audreyolafz** [comment]
I think it might be too crowded in the top section. Maybe it will be a better idea to change the heading "Horizon is a hackathon." into "Horizon is a magical one day coding party!"

**Comment by abbyfischler** [comment]
Oo ok go ahead and change!

**Comment by ymfpfp** [comment]
Done! What do you think?

**Comment by abbyfischler** [comment]
Looks great!!!!
